---

#setting facts to get around Tower:

- name: Define QA btsync_shared_folders:
  set_fact:
    btsync_shared_folders: "{{ QA_btsync_shared_folders }}"
  when: cluster_environment == "QA"

- name: Define PR btsync_shared_folders:
  set_fact:
    btsync_shared_folders: "{{ PR_btsync_shared_folders }}"
  when: cluster_environment == "PR"
  
- name: download
  get_url: url="{{ btsync_url[ansible_architecture] }}"
           dest=/tmp/btsync.tar.gz
  register: download

- name: extract
  command: tar xvzf /tmp/btsync.tar.gz -C /tmp
  when: download | changed

- name: copy btsync to /usr/local/bin
  command: cp /tmp/btsync /usr/local/bin/
  notify: start btsync
  when: download | changed

- name: install service
  template: src=btsync dest=/etc/init.d/btsync mode=755

- name: activate service
  service: name=btsync enabled=yes

- name: create .sync directory
  file: path=/home/{{ btsync_user }}/.sync owner={{ btsync_user }} group={{ btsync_user }} mode=0700 state=directory

- name: copy config
  template: src=config.json dest=/home/{{ btsync_user }}/.sync/ owner={{ btsync_user }} group={{ btsync_user }} mode=700
  notify: restart btsync

- name: create folders
  file: path={{ item.path }} recurse=yes state=directory owner={{ btsync_user }} group={{ btsync_user }} mode=700
  with_items: btsync_shared_folders
  when: btsync_shared_folders is defined

